#import "/prelude.typ": *

= Representations
We have seen how we can represent SP with at least 4 representation types:
- *Time domain*
$y(t) = a_1 y(t) + a_2 y(t-1) + ... + a_n y(t-m) + c_0 e(t) + b_1 e(t-1) + ... + c_n u(t-n)$

- *Operatorial* (Transfer function)
$y(t) = C(z) / A(z) e(t)$

- *Probabilistic*
$m_y(t) = E[y(t)]$

$gamma_y(tau) = E[(y(t) - m_y(t)) (y(t-tau) - m_y(t-tau))]$

- *Frequency domain*
$m_y(t) = E[y(t)]$

$Gamma(omega) = sum_(-infinity)^(+infinity) gamma_y(t) e^(-j omega tau)$

#remark[
  Reliable forecasts are based on unique representations.
  It is possible to represent a class of equivalent SP in different representations, but for each of them there are infinitely many representations $W(z)$, $e(t)$ that produce a specific given $y(t)$ as outcome.

  Some cases follow:

  Cases:

  - $y(t) = W(z) e(t)$
  1. $y(t) = W(z) alpha / alpha e(t)
    cases(
      tilde(W)(z) = W(z) / alpha,
      tilde(e)(t) = alpha e(t)
    )$

  2. $y(t) = W(z) z^n / z^n e(t)
    cases(
      tilde(W)(z) = W(z) z^n,
      tilde(e)(t) = z^{-n} e(t) = e(t-n)
    )$

  3. $y(t) = W(z) (z-p) / (z-p) e(t) , p in CC, abs(p)<1
    cases(
      tilde(W)(z) = W(z) (z-p) / (z-p),
      tilde(e)(t) = e(t)
    )$
  has a different difference equation than the original one but same dynamics.

  4. $y(t) = W(z) 1 / q (z-q) / (z-1 / q) e(t) , p in CC, abs(p)>1$

  Which is dimostrably equivalent $Gamma_y(t) = abs(Gamma(e^{j omega}))^2 = Gamma_e(omega)$

]

For each of these possible cases, we can define properties so to define a SSP in a unique way, selecting a *Canonical representation*.

#theorem(title: "Canonical representation")[
  A SSP is uniquely defined by a *canonical representation*.

  Let $y(t)$ be a SSP with a *rational* $Gamma_y(omega) in QQ$.

  Then there exists a unique representation $W(z)$, $e(t)$ such that $y(t) = W(z) e(t)$ and \ $W(z)= C(z)/A(z), z in CC$ if the following conditions hold:
  + $$C(z), A(z)$,$ are *monic*: the leading coefficient is 1 \ $cases(
      C(z) = 1 + c_1z^{-1} + ... + c_n z^{-n},
      A(z) = 1 + a_1z^{-1} + ... + a_m z^{-m}
    )$
  + $C(z), A(z)$ have *null relative degree*: $nu = n- m$
  + $C(z), A(z)$ are *coprime*: the greatest common divisor is 1
  + $C(z)$ has all roots in the *closed* unit circle ($|z_i| <= 1$), and $A(z)$ has all roots in the *open* unit circle ($|z_i| < 1$)

  $hat(W)(z)$ takes the name of *canonical spectral factor*.

] <thm:canonical-representation>

#remark(title: "Rationality constraint")[
  The canonical representation exists only for processes with *rational* spectrum $Gamma(omega)$. This corresponds to processes that can be generated by filtering white noise through a rational transfer function $W(z) = C(z)/A(z)$.
]

#remark(title: "Why the canonical form matters")[
  Each of the 4 sources of redundancy (scaling, time shift, pole/zero addition, all-pass filter) is eliminated by a corresponding condition:
  + Monic $arrow.r$ eliminates scaling redundancy
  + Same degree $arrow.r$ eliminates time shift redundancy
  + Coprime $arrow.r$ eliminates common factor redundancy
  + Roots inside unit circle $arrow.r$ eliminates all-pass filter redundancy
]

=== All-pass filter and spectrum invariance

#figure(
  {
    import fletcher: diagram, edge, node
    diagram(
      spacing: (2em, 1em),
      node-stroke: 1pt,
      node-shape: "rect",
      {
        // Input
        node((-1.5, 0), stroke: none)[$e(t)$\ $lambda^2$\ #text(fill: red, weight: "bold")[WN]]
        edge((-1.5, 0), (0, 0), "-|>")

        // Transfer function
        node((0, 0))[$display(frac(1 + c z^(-1), 1 + a z^(-1)))$\ #text(size: 8pt)[$c = 1 slash a$]]
        edge((0, 0), (1.5, 0), "-|>")

        // Output
        node((1.5, 0), stroke: none)[$y(t)$\ $c^2 lambda^2$\ #text(fill: red, weight: "bold")[WN]]

        // Label
        node((3, 0), stroke: none)[#text(fill: red, weight: "bold", size: 12pt)[ALL PASS\ FILTER]]
      },
    )
  },
  caption: [The all-pass filter with $c = 1/a$ transforms $e(t) tilde WN(0, lambda^2)$ into $y(t) tilde WN(0, c^2 lambda^2)$: the spectrum shape is preserved, only the variance changes.],
)

#theorem(title: "All-pass filter property")[
  Let $T(z) = 1/q dot (z - q)/(z - 1/q)$ with $|q| > 1$. Then:
  $ T(z) T(z^(-1)) = 1 $

  Multiplying $W(z)$ by $T(z)$ changes the transfer function but *preserves the spectrum*:
  $
    tilde(Phi)(z) = tilde(W)(z) tilde(W)(z^(-1)) lambda^2 = W(z) underbrace(T(z) T(z^(-1)), =1) W(z^(-1)) lambda^2 = Phi(z)
  $
]

#remark[
  The all-pass filter essentially replaces a singularity $q$ with its reciprocal $1/q$. This is why the canonical form requires roots inside the unit circle — it selects the unique representation where no all-pass transformation can be applied.
]

=== Examples

#example(title: "ARMA(1,1) canonical representation")[
  Let $v(t) = a v(t-1) + e(t) + c e(t-1)$, $e(t) tilde WN(0, lambda^2)$, with $|a| < 1$.

  $ Gamma(omega) = (1 + c^2 + 2c cos(omega)) / (1 + a^2 - 2a cos(omega)) lambda^2 $

  - If $|c| <= 1$: the representation is already canonical with $hat(W)(z) = (1 + c z^(-1))/(1 - a z^(-1))$
  - If $|c| > 1$: the canonical representation becomes $hat(W)(z) = (1 + 1/c dot z^(-1))/(1 - a z^(-1))$ with $hat(e)(t) tilde WN(0, c^2 lambda^2)$
]

#example(title: "Sum of independent processes")[
  Let $v(t) = xi(t-1) + eta(t) - eta(t-1)$ where $xi tilde WN(0, lambda_1^2)$ and $eta tilde WN(0, lambda_2^2)$ are independent.

  The process is the sum of a WN and an MA(1), hence stationary with $gamma(tau) = 0$ for $|tau| > 1$.

  It can be reformulated as $v(t) = epsilon(t) + c epsilon(t-1)$, $epsilon tilde WN(0, lambda^2)$ where $c, lambda^2$ are found by matching:
  $ cases(gamma(0) = (1+c^2)lambda^2 = lambda_1^2 + 2 lambda_2^2, gamma(1) = c lambda^2 = -lambda_2^2) $

  The canonical solution is the one with $|c| <= 1$.
]

